# Generated by Django 5.2.7 on 2025-10-13 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_image_project_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='division_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
