# Generated by Django 5.2.7 on 2025-10-13 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_category_project_division_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='goal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
